name: Check broken links

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  broken-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Mintlify CLI
        run: npm i -g mint

      - name: Check for broken links
        run: mint broken-links
